// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      '../../libs/underscore': {
        exports: "_"
      },
      '../../libs/backbone': {
        deps: ['../../libs/underscore', 'jquery'],
        exports: 'Backbone'
      },
      'models/Device': {
        deps: ['../../libs/underscore', '../../libs/backbone', 'jquery'],
        exports: 'Device'
      },
      'models/DeviceCollection': {
        deps: ['../../libs/underscore', '../../libs/backbone', 'jquery', 'models/Device'],
        exports: 'DeviceCollection',
        'BadgeAnimator': {
          deps: [],
          exports: 'BadgeAnimator'
        }
      }
    }
  });

  define(['jquery', '../../libs/underscore', '../../libs/backbone', 'models/Device', 'models/DeviceCollection', 'BadgeAnimator'], function($, _, Backbone, Device, DeviceCollection, BadgeAnimator) {
    var badge, devices;
    badge = new this.BadgeAnimator();
    devices = new DeviceCollection([], {
      badge: badge
    });
    devices.model = Device;
    return devices.poll(parseInt(localStorage["munin_monitor_interval"]));
  });

}).call(this);
